language: php

php:
  - 7.0
  
script:
  - composer config -g github-oauth.github.com $composer
  - composer config secure-http false
  - composer update --ignore-platform-reqs
 
after_success:
  - wget http://dev-yunc.pantheonsite.io/waspthemes-yellow-pencil.zip
  - wget http://dev-yunc.pantheonsite.io/businesslounge.zip
  - wget http://dev-yunc.pantheonsite.io/Archive.zip
  - unzip Archive.zip ./public/wp-content/themes
  - unzip businesslounge.zip ./public/wp-content/themes
  - unzip waspthemes-yellow-pencil.zip ./public/wp-content/plugins
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git checkout -b source
  - git push --quiet --force https://$wordpress@github.com/fydy/heroku.git source
  - rm -rf .travis.yml
  - mv travis.yml .travis.yml
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git checkout -b heroku
  - git push --quiet --force https://$wordpress@github.com/fydy/heroku.git heroku
