language: php

php:
  - 7.2
  
script:
  - composer config secure-http false
  - composer update --ignore-platform-reqs
 
after_success:
  - rm -rf .git
  - git init
  - git remote add origin git@github.com:fydy/heroku-wp.git
  - git checkout source
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git push --quiet --force https://$heroku@github.com/fydy/heroku-wp.git source
