language: php

php:
  - 7.0
  
script:
  - composer config secure-http false
  - composer update --ignore-platform-reqs
 
after_success:
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git checkout -b source
  - git push --quiet --force https://$wordpress@github.com/fydy/heroku.git source
  - git checkout -b heroku
  - git push --quiet --force https://$wordpress@github.com/fydy/heroku.git heroku
