language: php

php:
  - 7.2

before_script:
  - composer install
  
script:
  - composer update
 
after_success:
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git checkout source
- git push --quiet --force https://$heroku@github.com/fydy/heroku-wp.git source
  
 
