language: php

php:
  - 7.2
  
script:
  - composer config secure-http false
  - composer update --ignore-platform-reqs
 
after_success:
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  - git checkout -b source
  - git push --quiet --force https://$heroku@github.com/fydy/heroku-wp.git source
